module DcScheduler
  module Constants
    SCHEDULE_EXECUTION_INITIALIZING = 'INITIALIZING'
    SCHEDULE_EXECUTION_INIT_FAILED = 'INIT_FAILED'
    SCHEDULE_EXECUTION_RUNNING = 'RUNNING'
    SCHEDULE_EXECUTION_FAILED = 'FAILED'
    SCHEDULE_EXECUTION_PARTIALLY_SUCCESSFUL = 'PARTIALLY_SUCCESSFUL'
    SCHEDULE_EXECUTION_SUCCESSFUL = 'SUCCESSFUL'
    SCHEDULE_EXECUTION_CANCELED = 'CANCELED'
  end
end